//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "BICDirectoryEntryAccounts", "BICDirectoryEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication2.BICDirectoryEntry), "Accounts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.Accounts), true)]
[assembly: EdmRelationshipAttribute("Model1", "ParticipantInfoBICDirectoryEntry", "ParticipantInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication2.ParticipantInfo), "BICDirectoryEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication2.BICDirectoryEntry))]

#endregion

namespace WindowsFormsApplication2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Accounts> AccountsSet
        {
            get
            {
                if ((_AccountsSet == null))
                {
                    _AccountsSet = base.CreateObjectSet<Accounts>("AccountsSet");
                }
                return _AccountsSet;
            }
        }
        private ObjectSet<Accounts> _AccountsSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ParticipantInfo> ParticipantInfoSet
        {
            get
            {
                if ((_ParticipantInfoSet == null))
                {
                    _ParticipantInfoSet = base.CreateObjectSet<ParticipantInfo>("ParticipantInfoSet");
                }
                return _ParticipantInfoSet;
            }
        }
        private ObjectSet<ParticipantInfo> _ParticipantInfoSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BICDirectoryEntry> BICDirectoryEntrySet
        {
            get
            {
                if ((_BICDirectoryEntrySet == null))
                {
                    _BICDirectoryEntrySet = base.CreateObjectSet<BICDirectoryEntry>("BICDirectoryEntrySet");
                }
                return _BICDirectoryEntrySet;
            }
        }
        private ObjectSet<BICDirectoryEntry> _BICDirectoryEntrySet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccountsSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccountsSet(Accounts accounts)
        {
            base.AddObject("AccountsSet", accounts);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ParticipantInfoSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParticipantInfoSet(ParticipantInfo participantInfo)
        {
            base.AddObject("ParticipantInfoSet", participantInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BICDirectoryEntrySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBICDirectoryEntrySet(BICDirectoryEntry bICDirectoryEntry)
        {
            base.AddObject("BICDirectoryEntrySet", bICDirectoryEntry);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Accounts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Accounts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Accounts object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="account">Initial value of the Account property.</param>
        /// <param name="regulationAccountType">Initial value of the RegulationAccountType property.</param>
        /// <param name="cK">Initial value of the CK property.</param>
        /// <param name="accountCBRBIC">Initial value of the AccountCBRBIC property.</param>
        /// <param name="dateIn">Initial value of the DateIn property.</param>
        /// <param name="accountStatus">Initial value of the AccountStatus property.</param>
        /// <param name="bICDirectoryEntryId">Initial value of the BICDirectoryEntryId property.</param>
        public static Accounts CreateAccounts(global::System.Int32 id, global::System.String account, global::System.String regulationAccountType, global::System.String cK, global::System.String accountCBRBIC, global::System.String dateIn, global::System.String accountStatus, global::System.Int32 bICDirectoryEntryId)
        {
            Accounts accounts = new Accounts();
            accounts.Id = id;
            accounts.Account = account;
            accounts.RegulationAccountType = regulationAccountType;
            accounts.CK = cK;
            accounts.AccountCBRBIC = accountCBRBIC;
            accounts.DateIn = dateIn;
            accounts.AccountStatus = accountStatus;
            accounts.BICDirectoryEntryId = bICDirectoryEntryId;
            return accounts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Account
        {
            get
            {
                return _Account;
            }
            set
            {
                OnAccountChanging(value);
                ReportPropertyChanging("Account");
                _Account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Account");
                OnAccountChanged();
            }
        }
        private global::System.String _Account;
        partial void OnAccountChanging(global::System.String value);
        partial void OnAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RegulationAccountType
        {
            get
            {
                return _RegulationAccountType;
            }
            set
            {
                OnRegulationAccountTypeChanging(value);
                ReportPropertyChanging("RegulationAccountType");
                _RegulationAccountType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RegulationAccountType");
                OnRegulationAccountTypeChanged();
            }
        }
        private global::System.String _RegulationAccountType;
        partial void OnRegulationAccountTypeChanging(global::System.String value);
        partial void OnRegulationAccountTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CK
        {
            get
            {
                return _CK;
            }
            set
            {
                OnCKChanging(value);
                ReportPropertyChanging("CK");
                _CK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CK");
                OnCKChanged();
            }
        }
        private global::System.String _CK;
        partial void OnCKChanging(global::System.String value);
        partial void OnCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccountCBRBIC
        {
            get
            {
                return _AccountCBRBIC;
            }
            set
            {
                OnAccountCBRBICChanging(value);
                ReportPropertyChanging("AccountCBRBIC");
                _AccountCBRBIC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccountCBRBIC");
                OnAccountCBRBICChanged();
            }
        }
        private global::System.String _AccountCBRBIC;
        partial void OnAccountCBRBICChanging(global::System.String value);
        partial void OnAccountCBRBICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateIn
        {
            get
            {
                return _DateIn;
            }
            set
            {
                OnDateInChanging(value);
                ReportPropertyChanging("DateIn");
                _DateIn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateIn");
                OnDateInChanged();
            }
        }
        private global::System.String _DateIn;
        partial void OnDateInChanging(global::System.String value);
        partial void OnDateInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccountStatus
        {
            get
            {
                return _AccountStatus;
            }
            set
            {
                OnAccountStatusChanging(value);
                ReportPropertyChanging("AccountStatus");
                _AccountStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccountStatus");
                OnAccountStatusChanged();
            }
        }
        private global::System.String _AccountStatus;
        partial void OnAccountStatusChanging(global::System.String value);
        partial void OnAccountStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BICDirectoryEntryId
        {
            get
            {
                return _BICDirectoryEntryId;
            }
            set
            {
                OnBICDirectoryEntryIdChanging(value);
                ReportPropertyChanging("BICDirectoryEntryId");
                _BICDirectoryEntryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BICDirectoryEntryId");
                OnBICDirectoryEntryIdChanged();
            }
        }
        private global::System.Int32 _BICDirectoryEntryId;
        partial void OnBICDirectoryEntryIdChanging(global::System.Int32 value);
        partial void OnBICDirectoryEntryIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "BICDirectoryEntryAccounts", "BICDirectoryEntry")]
        public BICDirectoryEntry BICDirectoryEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BICDirectoryEntry>("Model1.BICDirectoryEntryAccounts", "BICDirectoryEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BICDirectoryEntry>("Model1.BICDirectoryEntryAccounts", "BICDirectoryEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BICDirectoryEntry> BICDirectoryEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BICDirectoryEntry>("Model1.BICDirectoryEntryAccounts", "BICDirectoryEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BICDirectoryEntry>("Model1.BICDirectoryEntryAccounts", "BICDirectoryEntry", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="BICDirectoryEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BICDirectoryEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BICDirectoryEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bIC">Initial value of the BIC property.</param>
        public static BICDirectoryEntry CreateBICDirectoryEntry(global::System.Int32 id, global::System.String bIC)
        {
            BICDirectoryEntry bICDirectoryEntry = new BICDirectoryEntry();
            bICDirectoryEntry.Id = id;
            bICDirectoryEntry.BIC = bIC;
            return bICDirectoryEntry;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BIC
        {
            get
            {
                return _BIC;
            }
            set
            {
                OnBICChanging(value);
                ReportPropertyChanging("BIC");
                _BIC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BIC");
                OnBICChanged();
            }
        }
        private global::System.String _BIC;
        partial void OnBICChanging(global::System.String value);
        partial void OnBICChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "BICDirectoryEntryAccounts", "Accounts")]
        public EntityCollection<Accounts> Accounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Accounts>("Model1.BICDirectoryEntryAccounts", "Accounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Accounts>("Model1.BICDirectoryEntryAccounts", "Accounts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ParticipantInfoBICDirectoryEntry", "ParticipantInfo")]
        public ParticipantInfo ParticipantInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParticipantInfo>("Model1.ParticipantInfoBICDirectoryEntry", "ParticipantInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParticipantInfo>("Model1.ParticipantInfoBICDirectoryEntry", "ParticipantInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParticipantInfo> ParticipantInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParticipantInfo>("Model1.ParticipantInfoBICDirectoryEntry", "ParticipantInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParticipantInfo>("Model1.ParticipantInfoBICDirectoryEntry", "ParticipantInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ParticipantInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ParticipantInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ParticipantInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ParticipantInfo CreateParticipantInfo(global::System.Int32 id)
        {
            ParticipantInfo participantInfo = new ParticipantInfo();
            participantInfo.Id = id;
            return participantInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameP
        {
            get
            {
                return _NameP;
            }
            set
            {
                OnNamePChanging(value);
                ReportPropertyChanging("NameP");
                _NameP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameP");
                OnNamePChanged();
            }
        }
        private global::System.String _NameP;
        partial void OnNamePChanging(global::System.String value);
        partial void OnNamePChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CntrCd
        {
            get
            {
                return _CntrCd;
            }
            set
            {
                OnCntrCdChanging(value);
                ReportPropertyChanging("CntrCd");
                _CntrCd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CntrCd");
                OnCntrCdChanged();
            }
        }
        private global::System.String _CntrCd;
        partial void OnCntrCdChanging(global::System.String value);
        partial void OnCntrCdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rgn
        {
            get
            {
                return _Rgn;
            }
            set
            {
                OnRgnChanging(value);
                ReportPropertyChanging("Rgn");
                _Rgn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rgn");
                OnRgnChanged();
            }
        }
        private global::System.String _Rgn;
        partial void OnRgnChanging(global::System.String value);
        partial void OnRgnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ind
        {
            get
            {
                return _Ind;
            }
            set
            {
                OnIndChanging(value);
                ReportPropertyChanging("Ind");
                _Ind = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ind");
                OnIndChanged();
            }
        }
        private global::System.String _Ind;
        partial void OnIndChanging(global::System.String value);
        partial void OnIndChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ParticipantInfoBICDirectoryEntry", "BICDirectoryEntry")]
        public BICDirectoryEntry BICDirectoryEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BICDirectoryEntry>("Model1.ParticipantInfoBICDirectoryEntry", "BICDirectoryEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BICDirectoryEntry>("Model1.ParticipantInfoBICDirectoryEntry", "BICDirectoryEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BICDirectoryEntry> BICDirectoryEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BICDirectoryEntry>("Model1.ParticipantInfoBICDirectoryEntry", "BICDirectoryEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BICDirectoryEntry>("Model1.ParticipantInfoBICDirectoryEntry", "BICDirectoryEntry", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
